test = {
    "type": "Pistols",
    "weaponName": "M44",
    "image": "https://cdn.gametools.network/weapons/bf6/T_UI_RagingHunter_PKG_Factory_MED-f9773307.webp",
    "altImage": "https://cdn.gametools.network/weapons/bf6/white/T_UI_RagingHunter_PKG_Factory_MED-f9773307.webp",
    "translationId": "ID_ABILITY_RH44",
    "name": "M44",
    "id": "wp_pst_m44",
    "kills": 0,
    "damage": 0,
    "assistsDamage": 0,
    "bodyKills": 0,
    "headshotKills": 0,
    "hipfireKills": 0,
    "multiKills": 0,
    "accuracy": 0.0,
    "killsPerMinute": 0.0,
    "damagePerMinute": 0.0,
    "headshots": 0.0,
    "hitVKills": 0.0,
    "shotsHit": 0,
    "shotsFired": 0,
    "scopedKills": 0,
    "spawns": 0,
    "timeEquipped": 0,
}


val = {
    "type": "Assault Rifles",
    "weaponName": "VCR-2",
    "image": "https://cdn.gametools.network/weapons/bf6/T_UI_VHS2_Factory_Icon-a82fc1f9.webp",
    "altImage": "https://cdn.gametools.network/weapons/bf6/white/T_UI_VHS2_Factory_Icon-a82fc1f9.webp",
    "translationId": "ID_ABILITY_VHS2",
    "name": "VCR-2",
    "id": "wp_ar_vhsk2",
    "kills": 0,
    "damage": 0,
    "assistsDamage": 0,
    "bodyKills": 0,
    "headshotKills": 0,
    "hipfireKills": 0,
    "multiKills": 0,
    "accuracy": 0.0,
    "killsPerMinute": 0.0,
    "damagePerMinute": 0.0,
    "headshots": 0.0,
    "hitVKills": 0.0,
    "shotsHit": 0,
    "shotsFired": 0,
    "scopedKills": 0,
    "spawns": 0,
    "timeEquipped": 0,
}

print(all([not x for x in val.values() if not isinstance(x, str)]))
